package dataEnum;

public enum NaturaConti { 
	
	// R=RICAVI C= COSTI -> CONTO ECONOMICO 
	R_VENDITE_PRESTAZ,
	R_PROVENTI_FINANZIARI,//conterrà partecipazioni e altri proventi finanziari
	R_RIVALUTAZIONI,
	R_PROVENTI_STRAORD,
	C_MATERIE,
	C_SERVIZI,
	C_BENI_DI_TERZI,
	C_PERSONALE,
	C_AMMORTAMENTI_SVALUTAZIONI,
	C_ACCANTONAMENTI,
	C_ONERI_DI_GESTIONE,
	C_ONERI_FINANZIARI,	//conterrà interessi e utili+perdite su cambi	
	C_SVALUTAZIONI,
	C_ONERI_STRAORD,
	C_IMPOSTE,
	
	//ATT = ATTIVITA' PASS = PAVVIVITA' -> STATO PATRIMONIALE
	ATT_CRED_VS_SOCI,
	ATT_IMMO_MATERIALI,
	ATT_IMMO_IMMATERIALI,
	ATT_IMMO_FINANZIARIE,
	ATT_CREDITI,
	ATT_RIMANENZE,
	ATT_ATTIVITA_FINANZ,
	ATT_DISP_LIQU,
	ATT_RATEI_RISCONTI,
	PASS_PATR_NETTO,
	PASS_FONDI,
	PASS_TFR,
	PASS_DEBITI,
	PASS_RATEI_RISCONTI
}
